FROM --platform=linux/amd64 mcr.microsoft.com/dotnet/core/runtime:3.1-buster-slim

USER root

RUN apt-get update
RUN apt-get -y install locales libicu-dev && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8

RUN apt-get update && apt-get install -y libicu-dev

ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ JST-9
ENV TERM xterm
ENV System.Globalization.Invariant=true